version: 2.1

filters-release: &filters-release
  tags:
    only: 
      - /^v.*/
  branches:
    ignore: /.*/

orbs:
  go: circleci/go@1.7.3

commands:
  prepare-publish-artifacts:
    parameters:
      platform:
        type: string
        default: "linux-amd64"
      file_extension:
        type: string
        default: ""
    steps:
      - run: |
          cp build/bin/gzond<< parameters.file_extension >> /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          (cd /tmp && sha256sum gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >> > gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256)

          # TODO(rgeraldes24): replace default key with the new one
          echo -n "$GPG_KEY" | base64 --decode | gpg --import
          gpg -o /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig --default-key C6A8251946339065ECE9B1553D2EF77E42EB27AE --sign --detach-sig /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=qrysm tag=${CIRCLE_TAG} filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=qrysm tag=${CIRCLE_TAG} filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=qrysm tag=${CIRCLE_TAG} filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig

jobs:
  publish-linux-amd64-gzond-binary:
    executor:
      name: go/default
      tag: '1.20.13'
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - go/load-cache 
      - go/mod-download
      - go/save-cache
      - steps: |
          go run build/ci.go install ./cmd/gzond
      - prepare-publish-artifacts:
          platform: "linux-amd64"
          
workflows:
  release:
    jobs:
      - publish-linux-amd64-gzond-binary:
          # filters:
          #   <<: *filters-release
      # - publish-linux-arm64-gzond-binary:
      #     filters:
      #       <<: *filters-release
      # - publish-darwin-amd64-gzond-binary:
      #     filters:
      #       <<: *filters-release
      # - publish-darwin-arm64-gzond-binary:
      #     filters:
      #       <<: *filters-release
      # - publish-windows-amd64-gzond-binary:
      #     filters: 
      #       <<: *filters-release