version: 2.1

filters-release: &filters-release
  tags:
    only: 
      - /^v.*/
  branches:
    ignore: /.*/

commands:
  prepare-publish-artifacts:
    parameters:
      platform:
        type: string
        default: "linux-amd64"
      file_extension:
        type: string
        default: ""
    steps:
      - run: |
          cp build/bin/gzond<< parameters.file_extension >> /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          (cd /tmp && sha256sum gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >> > gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256)

          # TODO(rgeraldes24): replace default key with the new one
          echo -n "$GPG_KEY" | base64 --decode | gpg --import
          gpg -o /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig --default-key 48DEF40BDA94D5F361B0CBCEEC1ACE3DEFECD129 --sign --detach-sig /tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=go-zond tag=v0.1.0 filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=go-zond tag=v0.1.0 filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=go-zond tag=v0.1.0 filename=/tmp/gzond-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig

jobs:
  publish-linux-amd64-gzond-binary:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run: |
          go run build/ci.go install ./cmd/gzond
      - prepare-publish-artifacts:
          platform: "linux-amd64"
  
  publish-linux-arm64-gzond-binary:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run: |
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          go run build/ci.go install -arch arm -cc arm-linux-gnueabi-gcc
      - prepare-publish-artifacts:
          platform: "linux-arm64"
          
workflows:
  release:
    jobs:
      #- publish-linux-amd64-gzond-binary
          # filters:
          #   <<: *filters-release
      - publish-linux-arm64-gzond-binary
      #     filters:
      #       <<: *filters-release
      # - publish-darwin-amd64-gzond-binary:
      #     filters:
      #       <<: *filters-release
      # - publish-darwin-arm64-gzond-binary:
      #     filters:
      #       <<: *filters-release
      # - publish-windows-amd64-gzond-binary:
      #     filters: 
      #       <<: *filters-release